// Code generated by mockery v2.53.3. DO NOT EDIT.

package storage_mocks

import mock "github.com/stretchr/testify/mock"

// StorageInterface is an autogenerated mock type for the StorageInterface type
type StorageInterface struct {
	mock.Mock
}

// GetRefreshTokenHash provides a mock function with given fields: userId
func (_m *StorageInterface) GetRefreshTokenHash(userId string) (string, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserEmail provides a mock function with given fields: userId
func (_m *StorageInterface) GetUserEmail(userId string) (string, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveRefreshTokenHash provides a mock function with given fields: userId, refrTokenHash
func (_m *StorageInterface) SaveRefreshTokenHash(userId string, refrTokenHash string) error {
	ret := _m.Called(userId, refrTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userId, refrTokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRefreshTokenHash provides a mock function with given fields: userId, newRefrTokenHash
func (_m *StorageInterface) UpdateRefreshTokenHash(userId string, newRefrTokenHash string) error {
	ret := _m.Called(userId, newRefrTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userId, newRefrTokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorageInterface creates a new instance of StorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageInterface {
	mock := &StorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
